let ogh = {
    "id": "8276b5af-83de-48ef-8363-dfe829b46399-1850dda5",
    "fulfillmentText": "<speak><audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio><prosody rate=\"medium\" pitch=\"1st\"> Please say operator </prosody></speak>",
    "language_code": "en",
    "queryText": "TELEPHONY_WELCOME",
    "webhookPayload": {},
    "intentDetectionConfidence": 1,
    "action": "get_name_ymm",
    "webhookSource": "",
    "parameters": {
      "apiName": "apiRequiresCustomerName",
      "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
      "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
      "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
      "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
      "advisorEmail": "booking@allio.io",
      "customerPhone": "",
      "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
      "example": "SPORTAGE",
      "fallbackService": "DIAG",
      "advisorNumber": "13",
      "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
      "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
      "getDataFromDB": "x-5-wpawpy",
      "businessPhone": "5737790808",
      "email": "allioforbus@gmail.com",
      "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
      "make": "Kia",
      "recallService": "DIAG",
      "businessName": "Kia of Alhambra"
    },
    "fulfillmentMessages": [
      {
        "platform": "TELEPHONY",
        "telephonySynthesizeSpeech": {
          "ssml": "<speak><audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio><prosody rate=\"medium\" pitch=\"1st\"> Please say operator </prosody></speak>"
        }
      },
      {
        "text": {
          "text": [
            "<speak><audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio><prosody rate=\"medium\" pitch=\"1st\"> Please say operator </prosody></speak>"
          ]
        }
      }
    ],
    "diagnosticInfo": {
      "webhook_latency_ms": "4893.0"
    },
    "webhookStatus": {
      "webhookStatus": {
        "code": 4,
        "message": "Webhook call failed. Error: DEADLINE_EXCEEDED, State: URL_TIMEOUT, Reason: TIMEOUT_WEB."
      },
      "webhookUsed": true
    },
    "outputContexts": [
      {
        "lifespanCount": 99,
        "name": "config",
        "parameters": {
          "businessName.original": "",
          "advisorNumber.original": "",
          "customerPhone": "",
          "book_url.original": "",
          "WeekOpenCloseSatOpenClose.original": "",
          "make.original": "",
          "advisorEmail.original": "",
          "check_url.original": "",
          "greeting.original": "",
          "email.original": "",
          "prompt.original": "",
          "getDataFromDB.original": "",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "advisorEmail": "booking@allio.io",
          "advisorNumber": "13",
          "timeSlots.original": "",
          "example.original": "",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "recallService.original": "",
          "example": "SPORTAGE",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "businessName": "Kia of Alhambra",
          "businessPhone": "5737790808",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "make": "Kia",
          "recallService": "DIAG",
          "apiName.original": "",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "businessPhone.original": "",
          "transportQuestion2.original": "",
          "apiName": "apiRequiresCustomerName",
          "hoursLocation.original": "",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "fallbackService.original": "",
          "customerPhone.original": "",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "getDataFromDB": "x-5-wpawpy",
          "email": "allioforbus@gmail.com",
          "fallbackService": "DIAG"
        }
      },
      {
        "lifespanCount": 1,
        "name": "greeting",
        "parameters": {
          "transportQuestion2.original": "",
          "advisorEmail.original": "",
          "fallbackService.original": "",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "businessPhone.original": "",
          "advisorEmail": "booking@allio.io",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "recallService": "DIAG",
          "make.original": "",
          "email.original": "",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "customerPhone.original": "",
          "prompt.original": "",
          "apiName.original": "",
          "businessName": "Kia of Alhambra",
          "recallService.original": "",
          "email": "allioforbus@gmail.com",
          "businessPhone": "5737790808",
          "fallbackService": "DIAG",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "book_url.original": "",
          "example": "SPORTAGE",
          "example.original": "",
          "businessName.original": "",
          "timeSlots.original": "",
          "greeting.original": "",
          "getDataFromDB": "x-5-wpawpy",
          "make": "Kia",
          "customerPhone": "",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "WeekOpenCloseSatOpenClose.original": "",
          "getDataFromDB.original": "",
          "apiName": "apiRequiresCustomerName",
          "check_url.original": "",
          "advisorNumber": "13",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "hoursLocation.original": "",
          "advisorNumber.original": ""
        }
      },
      {
        "lifespanCount": 1,
        "name": "makeappt",
        "parameters": {
          "customerPhone": "",
          "transportQuestion2.original": "",
          "check_url.original": "",
          "getDataFromDB": "x-5-wpawpy",
          "prompt.original": "",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "email": "allioforbus@gmail.com",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "apiName": "apiRequiresCustomerName",
          "timeSlots.original": "",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "example": "SPORTAGE",
          "recallService.original": "",
          "make": "Kia",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "fallbackService.original": "",
          "businessPhone": "5737790808",
          "businessName": "Kia of Alhambra",
          "WeekOpenCloseSatOpenClose.original": "",
          "greeting.original": "",
          "hoursLocation.original": "",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "advisorNumber.original": "",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "book_url.original": "",
          "businessName.original": "",
          "email.original": "",
          "recallService": "DIAG",
          "businessPhone.original": "",
          "advisorEmail.original": "",
          "example.original": "",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "advisorNumber": "13",
          "apiName.original": "",
          "getDataFromDB.original": "",
          "customerPhone.original": "",
          "advisorEmail": "booking@allio.io",
          "make.original": "",
          "fallbackService": "DIAG",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336"
        }
      },
      {
        "lifespanCount": 1,
        "name": "noname-followup",
        "parameters": {
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "businessPhone.original": "",
          "advisorNumber": "13",
          "example.original": "",
          "customerPhone.original": "",
          "recallService": "DIAG",
          "advisorEmail": "booking@allio.io",
          "fallbackService": "DIAG",
          "fallbackService.original": "",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "recallService.original": "",
          "email.original": "",
          "WeekOpenCloseSatOpenClose.original": "",
          "businessPhone": "5737790808",
          "book_url.original": "",
          "hoursLocation.original": "",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "customerPhone": "",
          "prompt.original": "",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "advisorNumber.original": "",
          "transportQuestion2.original": "",
          "businessName": "Kia of Alhambra",
          "greeting.original": "",
          "make.original": "",
          "example": "SPORTAGE",
          "email": "allioforbus@gmail.com",
          "apiName": "apiRequiresCustomerName",
          "getDataFromDB": "x-5-wpawpy",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "make": "Kia",
          "check_url.original": "",
          "apiName.original": "",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "advisorEmail.original": "",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "timeSlots.original": "",
          "businessName.original": "",
          "getDataFromDB.original": ""
        }
      },
      {
        "lifespanCount": 99,
        "name": "transferoperator",
        "parameters": {
          "example.original": "",
          "book_url.original": "",
          "getDataFromDB": "x-5-wpawpy",
          "email.original": "",
          "email": "allioforbus@gmail.com",
          "make.original": "",
          "check_url.original": "",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "fallbackService": "DIAG",
          "advisorNumber.original": "",
          "prompt.original": "",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "recallService": "DIAG",
          "businessName": "Kia of Alhambra",
          "WeekOpenCloseSatOpenClose.original": "",
          "businessPhone.original": "",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "apiName": "apiRequiresCustomerName",
          "customerPhone.original": "",
          "timeSlots.original": "",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "businessName.original": "",
          "advisorNumber": "13",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "advisorEmail.original": "",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "advisorEmail": "booking@allio.io",
          "customerPhone": "",
          "example": "SPORTAGE",
          "businessPhone": "5737790808",
          "make": "Kia",
          "greeting.original": "",
          "apiName.original": "",
          "hoursLocation.original": "",
          "fallbackService.original": "",
          "transportQuestion2.original": "",
          "getDataFromDB.original": "",
          "recallService.original": ""
        }
      },
      {
        "lifespanCount": 99,
        "name": "transfervm",
        "parameters": {
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "greeting.original": "",
          "fallbackService.original": "",
          "recallService.original": "",
          "WeekOpenCloseSatOpenClose.original": "",
          "apiName": "apiRequiresCustomerName",
          "advisorEmail.original": "",
          "advisorEmail": "booking@allio.io",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "example.original": "",
          "prompt.original": "",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "recallService": "DIAG",
          "businessPhone": "5737790808",
          "businessName.original": "",
          "advisorNumber": "13",
          "transportQuestion2.original": "",
          "businessName": "Kia of Alhambra",
          "businessPhone.original": "",
          "email": "allioforbus@gmail.com",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "getDataFromDB.original": "",
          "fallbackService": "DIAG",
          "getDataFromDB": "x-5-wpawpy",
          "hoursLocation.original": "",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "email.original": "",
          "check_url.original": "",
          "make.original": "",
          "book_url.original": "",
          "advisorNumber.original": "",
          "apiName.original": "",
          "example": "SPORTAGE",
          "customerPhone.original": "",
          "make": "Kia",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "customerPhone": "",
          "timeSlots.original": ""
        }
      },
      {
        "lifespanCount": 99,
        "name": "fixedline",
        "parameters": {
          "apiName": "apiRequiresCustomerName",
          "advisorNumber": "13",
          "customerPhone.original": "",
          "fallbackService.original": "",
          "book_url.original": "",
          "fallbackService": "DIAG",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "check_url.original": "",
          "recallService.original": "",
          "make.original": "",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "getDataFromDB": "x-5-wpawpy",
          "email": "allioforbus@gmail.com",
          "businessName": "Kia of Alhambra",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "recallService": "DIAG",
          "greeting.original": "",
          "transportQuestion2.original": "",
          "timeSlots.original": "",
          "advisorEmail": "booking@allio.io",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "businessName.original": "",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "prompt.original": "",
          "example.original": "",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "advisorNumber.original": "",
          "customerPhone": "",
          "businessPhone.original": "",
          "advisorEmail.original": "",
          "WeekOpenCloseSatOpenClose.original": "",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "getDataFromDB.original": "",
          "example": "SPORTAGE",
          "email.original": "",
          "make": "Kia",
          "apiName.original": "",
          "hoursLocation.original": "",
          "businessPhone": "5737790808"
        }
      },
      {
        "lifespanCount": 99,
        "name": "processrecall",
        "parameters": {
          "book_url.original": "",
          "getDataFromDB": "x-5-wpawpy",
          "prompt.original": "",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "customerPhone.original": "",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "apiName": "apiRequiresCustomerName",
          "make.original": "",
          "WeekOpenCloseSatOpenClose.original": "",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "fallbackService.original": "",
          "getDataFromDB.original": "",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "greeting.original": "",
          "check_url.original": "",
          "advisorEmail.original": "",
          "email.original": "",
          "businessPhone.original": "",
          "example": "SPORTAGE",
          "businessPhone": "5737790808",
          "hoursLocation.original": "",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "recallService": "DIAG",
          "advisorNumber.original": "",
          "email": "allioforbus@gmail.com",
          "customerPhone": "",
          "businessName.original": "",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "recallService.original": "",
          "apiName.original": "",
          "example.original": "",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "advisorEmail": "booking@allio.io",
          "fallbackService": "DIAG",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "timeSlots.original": "",
          "businessName": "Kia of Alhambra",
          "make": "Kia",
          "transportQuestion2.original": "",
          "advisorNumber": "13"
        }
      },
      {
        "lifespanCount": 99,
        "name": "adhoc",
        "parameters": {
          "fallbackService.original": "",
          "advisorNumber.original": "",
          "book_url.original": "",
          "greeting.original": "",
          "getDataFromDB": "x-5-wpawpy",
          "getDataFromDB.original": "",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "businessPhone.original": "",
          "apiName.original": "",
          "hoursLocation.original": "",
          "fallbackService": "DIAG",
          "make.original": "",
          "prompt.original": "",
          "recallService.original": "",
          "email": "allioforbus@gmail.com",
          "recallService": "DIAG",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "customerPhone": "",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "timeSlots.original": "",
          "example.original": "",
          "check_url.original": "",
          "advisorEmail.original": "",
          "businessPhone": "5737790808",
          "email.original": "",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "WeekOpenCloseSatOpenClose.original": "",
          "make": "Kia",
          "transportQuestion2.original": "",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "apiName": "apiRequiresCustomerName",
          "advisorEmail": "booking@allio.io",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "customerPhone.original": "",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "businessName.original": "",
          "advisorNumber": "13",
          "businessName": "Kia of Alhambra",
          "example": "SPORTAGE"
        }
      },
      {
        "lifespanCount": 99,
        "name": "dropin",
        "parameters": {
          "example": "SPORTAGE",
          "prompt.original": "",
          "timeSlots.original": "",
          "businessName": "Kia of Alhambra",
          "businessPhone.original": "",
          "hoursLocation.original": "",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "customerPhone": "",
          "apiName": "apiRequiresCustomerName",
          "apiName.original": "",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "example.original": "",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "greeting.original": "",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "make": "Kia",
          "transportQuestion2.original": "",
          "getDataFromDB": "x-5-wpawpy",
          "advisorNumber": "13",
          "make.original": "",
          "email": "allioforbus@gmail.com",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "email.original": "",
          "advisorEmail": "booking@allio.io",
          "businessPhone": "5737790808",
          "book_url.original": "",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "fallbackService.original": "",
          "WeekOpenCloseSatOpenClose.original": "",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "getDataFromDB.original": "",
          "customerPhone.original": "",
          "check_url.original": "",
          "businessName.original": "",
          "fallbackService": "DIAG",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "advisorEmail.original": "",
          "recallService": "DIAG",
          "advisorNumber.original": "",
          "recallService.original": ""
        }
      },
      {
        "lifespanCount": 99,
        "name": "compressed",
        "parameters": {
          "advisorNumber": "13",
          "WeekOpenCloseSatOpenClose": "7:30,18:00,7:30,18:00",
          "WeekOpenCloseSatOpenClose.original": "",
          "email.original": "",
          "businessPhone": "5737790808",
          "customerPhone": "",
          "hoursLocation": "Kia of Alhambra is located at 1247 West Main Street Alhambra. Our service department hours are, 7:30 AM to 6:00 PM, Monday through  Saturday",
          "fallbackService": "DIAG",
          "timeSlots": "MTWTF,START,09:10,END,16:00,PERIOD,20,S,START,10:00,END,14:00,PERIOD,20,SKIPHR-336",
          "example.original": "",
          "advisorNumber.original": "",
          "advisorEmail": "booking@allio.io",
          "prompt.original": "",
          "check_url.original": "",
          "greeting": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/BDC1-KH.ogg\">\nWelcome to Kia of Alhambra Service Department. This is Allio, your digital assistant. I can book appointments or get you the help you need. How can I assist you today?\n</audio>\n<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-HowCanIAssistYouToday.ogg\">\nHow can I assist you today?\n</audio>",
          "businessPhone.original": "",
          "getDataFromDB.original": "",
          "hoursLocation.original": "",
          "apiName.original": "",
          "email": "allioforbus@gmail.com",
          "make": "Kia",
          "apiName": "apiRequiresCustomerName",
          "book_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/book?id=KIAALHAMBRA&brand=KIA&address=1247 West Main St&city=Alhambra&state=CA&zip=91801&dealer=kiaofalhambra",
          "book_url.original": "",
          "businessName.original": "",
          "recallService": "DIAG",
          "check_url": "https://kj50zlv5ll.execute-api.us-east-1.amazonaws.com/myvehicle/check?id=KIAALHAMBRA&brand=KIA&dealer=kiaofalhambra",
          "recallService.original": "",
          "transportQuestion2.original": "",
          "prompt": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/S-PleaseSayMakeApptOrOther.ogg\">\nPlease say make appointment or say other</audio>",
          "getDataFromDB": "x-5-wpawpy",
          "make.original": "",
          "timeSlots.original": "",
          "greeting.original": "",
          "transportQuestion2": "<audio soundLevel=\"+15dB\" src=\"https://storage.googleapis.com/autoserviceai/dropOffOrWait.ogg\">Would you like drop off your vehicle or wait at the dealership?</audio>",
          "customerPhone.original": "",
          "advisorEmail.original": "",
          "businessName": "Kia of Alhambra",
          "fallbackService.original": "",
          "example": "SPORTAGE"
        }
      }
    ],
    "intent": {
      "isFallback": false,
      "displayName": "--1-Welcome-KH",
      "id": "cc4e0135-a883-48f3-b05c-ab27b567023e"
    }
}
let a 